test

diff --git a/.github/workflows/snyk-license-scan.yml b/.github/workflows/snyk-license-scan.yml
--- a/.github/workflows/snyk-license-scan.yml
+++ b/.github/workflows/snyk-license-scan.yml
@@ -82,37 +82,37 @@ jobs:
           # Store new vulnerability details for final output
           vuln_details=""
 
-          if [ -n "$new_vulns" ]; then
-            # Collect details for each new vulnerability
-            for vuln_id in $new_vulns; do
-              # Extract detailed information for each new vulnerability including CVE ID
-              vuln_info=$(jq --arg id "$vuln_id" '.vulnerabilities[] | select(.id == $id) | {
-                id: .id,
-                type: .type,
-                license: .license,
-                language: .language,
-                description: .description,
-                packageName: .packageName,
-                creationTime: .creationTime,
-                packageManager: .packageManager,
-                publicationTime: .publicationTime,
-                severity: .severity,
-                from: .from,
-                upgradePath: .upgradePath,
-                version: .version,
-                semver: .semver
-              }' current-report.json)
-
-              # Add this vulnerability info to the details string
-              vuln_details="$vuln_details\n$vuln_info"
-            done
-          fi
-
-          # Output results at the end
-          if [ -n "$new_vulns" ]; then
-            echo -e "\033[0;31mERROR: Your PR has introduced the following new vulnerabilities. Please ensure these vulnerabilities are fully addressed before the PR can be merged.\033[0m"
-            echo -e "\033[0;33mTotal new vulnerabilities found: $vuln_count\033[0m"
-            echo -e "\033[0;31mList of New Vulnerabilities:\033[0m"
-            echo -e "$vuln_details"
-            exit 1  # Fail CI if new vulnerabilities are found
-          fi
+#          if [ -n "$new_vulns" ]; then
+#            # Collect details for each new vulnerability
+#            for vuln_id in $new_vulns; do
+#              # Extract detailed information for each new vulnerability including CVE ID
+#              vuln_info=$(jq --arg id "$vuln_id" '.vulnerabilities[] | select(.id == $id) | {
+#                id: .id,
+#                type: .type,
+#                license: .license,
+#                language: .language,
+#                description: .description,
+#                packageName: .packageName,
+#                creationTime: .creationTime,
+#                packageManager: .packageManager,
+#                publicationTime: .publicationTime,
+#                severity: .severity,
+#                from: .from,
+#                upgradePath: .upgradePath,
+#                version: .version,
+#                semver: .semver
+#              }' current-report.json)
+#
+#              # Add this vulnerability info to the details string
+#              vuln_details="$vuln_details\n$vuln_info"
+#            done
+#          fi
+#
+#          # Output results at the end
+#          if [ -n "$new_vulns" ]; then
+#            echo -e "\033[0;31mERROR: Your PR has introduced the following new vulnerabilities. Please ensure these vulnerabilities are fully addressed before the PR can be merged.\033[0m"
+#            echo -e "\033[0;33mTotal new vulnerabilities found: $vuln_count\033[0m"
+#            echo -e "\033[0;31mList of New Vulnerabilities:\033[0m"
+#            echo -e "$vuln_details"
+#            exit 1  # Fail CI if new vulnerabilities are found
+#          fi
